version: '3.1'

networks:
  loki:

services:
  db:
    image: postgres
    restart: always
    ports:
      - '15000:5432'
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pguser
      POSTGRES_DB: pgdb
